// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentMVC.Data;

#nullable disable

namespace StudentMVC.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    partial class StudentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.33");

            modelBuilder.Entity("StudentMVC.Models.Entities.Degree", b =>
                {
                    b.Property<int>("DegreeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DegreeId");

                    b.ToTable("Degrees");

                    b.HasData(
                        new
                        {
                            DegreeId = 1,
                            Name = "Bachelor"
                        },
                        new
                        {
                            DegreeId = 2,
                            Name = "Master"
                        },
                        new
                        {
                            DegreeId = 3,
                            Name = "Phd"
                        });
                });

            modelBuilder.Entity("StudentMVC.Models.Entities.Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<int>("DegreeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Firstname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lastname")
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId");

                    b.HasIndex("DegreeId");

                    b.ToTable("Student", (string)null);

                    b.HasData(
                        new
                        {
                            StudentId = "ssa171",
                            DegreeId = 1,
                            Firstname = "Said",
                            Lastname = "Nasser"
                        },
                        new
                        {
                            StudentId = "jbe123",
                            DegreeId = 2,
                            Firstname = "Johnny",
                            Lastname = "BeGood"
                        },
                        new
                        {
                            StudentId = "mla789",
                            DegreeId = 1,
                            Firstname = "Morgan",
                            Lastname = "Larsen"
                        },
                        new
                        {
                            StudentId = "lpr058",
                            DegreeId = 3,
                            Firstname = "Linda",
                            Lastname = "Pravidin"
                        },
                        new
                        {
                            StudentId = "rol000",
                            DegreeId = 2,
                            Firstname = "Roy",
                            Lastname = "Olsen"
                        },
                        new
                        {
                            StudentId = "Ono456",
                            DegreeId = 3,
                            Firstname = "Ola",
                            Lastname = "Nordmann"
                        });
                });

            modelBuilder.Entity("StudentMVC.Models.Entities.Student", b =>
                {
                    b.HasOne("StudentMVC.Models.Entities.Degree", "Degree")
                        .WithMany("Students")
                        .HasForeignKey("DegreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Degree");
                });

            modelBuilder.Entity("StudentMVC.Models.Entities.Degree", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
